package com.amotassic.dabaosword.util;

import net.minecraft.sounds.SoundEvent;

public class Sounds {
    public static SoundEvent SHENSU = AllRegs.Sounds.SHENSU.get();
    public static SoundEvent LIANYING = AllRegs.Sounds.LIANYING.get();
    public static SoundEvent XIAOJI = AllRegs.Sounds.XIAOJI.get();
    public static SoundEvent LET_ME_CC = AllRegs.Sounds.LET_ME_CC.get();
    public static SoundEvent LONGDAN = AllRegs.Sounds.LONGDAN.get();
    public static SoundEvent GONGXIN = AllRegs.Sounds.GONGXIN.get();
    public static SoundEvent ZHIJIAN = AllRegs.Sounds.ZHIJIAN.get();
    public static SoundEvent SHANZHUAN = AllRegs.Sounds.SHANZHUAN.get();
    public static SoundEvent RENDE = AllRegs.Sounds.RENDE.get();
    public static SoundEvent ZHIHENG = AllRegs.Sounds.ZHIHENG.get();
    public static SoundEvent BUQU = AllRegs.Sounds.BUQU.get();
    public static SoundEvent TIEJI = AllRegs.Sounds.TIEJI.get();
    public static SoundEvent GANGLIE = AllRegs.Sounds.GANGLIE.get();
    public static SoundEvent FANGZHU = AllRegs.Sounds.FANGZHU.get();
    public static SoundEvent XINGSHANG = AllRegs.Sounds.XINGSHANG.get();
    public static SoundEvent BBJI = AllRegs.Sounds.BBJI.get();
    public static SoundEvent XUYOU = AllRegs.Sounds.XUYOU.get();
    public static SoundEvent DUANLIANG = AllRegs.Sounds.DUANLIANG.get();
    public static SoundEvent LUOSHEN = AllRegs.Sounds.LUOSHEN.get();
    public static SoundEvent QIXI = AllRegs.Sounds.QIXI.get();
    public static SoundEvent QINGGUO = AllRegs.Sounds.QINGGUO.get();
    public static SoundEvent LIEGONG = AllRegs.Sounds.LIEGONG.get();
    public static SoundEvent GONGAO = AllRegs.Sounds.GONGAO.get();
    public static SoundEvent WEIZHONG = AllRegs.Sounds.WEIZHONG.get();
    public static SoundEvent BENXI = AllRegs.Sounds.BENXI.get();
    public static SoundEvent LEIJI = AllRegs.Sounds.LEIJI.get();
    public static SoundEvent GIFTBOX = AllRegs.Sounds.GIFTBOX.get();
    public static SoundEvent KANPO = AllRegs.Sounds.KANPO.get();
    public static SoundEvent GUOSE = AllRegs.Sounds.GUOSE.get();
    public static SoundEvent LIULI = AllRegs.Sounds.LIULI.get();
    public static SoundEvent JUEQING = AllRegs.Sounds.JUEQING.get();
    public static SoundEvent LUANJI = AllRegs.Sounds.LUANJI.get();
    public static SoundEvent KUROU = AllRegs.Sounds.KUROU.get();
    public static SoundEvent JIZHI = AllRegs.Sounds.JIZHI.get();
    public static SoundEvent QICE = AllRegs.Sounds.QICE.get();
    public static SoundEvent LUOYI = AllRegs.Sounds.LUOYI.get();
    public static SoundEvent HUOJI = AllRegs.Sounds.HUOJI.get();
    public static SoundEvent QUANJI = AllRegs.Sounds.QUANJI.get();
    public static SoundEvent ZILI = AllRegs.Sounds.ZILI.get();
    public static SoundEvent PAIYI = AllRegs.Sounds.PAIYI.get();
    public static SoundEvent YIJI = AllRegs.Sounds.YIJI.get();
    public static SoundEvent TAOLUAN = AllRegs.Sounds.TAOLUAN.get();
    public static SoundEvent POJUN = AllRegs.Sounds.POJUN.get();
    public static SoundEvent KUANGGU = AllRegs.Sounds.KUANGGU.get();

    public static SoundEvent BAGUA = AllRegs.Sounds.BAGUA.get();
    public static SoundEvent BAIYIN = AllRegs.Sounds.BAIYIN.get();
    public static SoundEvent FANGTIAN = AllRegs.Sounds.FANGTIAN.get();
    public static SoundEvent GUDING = AllRegs.Sounds.GUDING.get();
    public static SoundEvent HANBING = AllRegs.Sounds.HANBING.get();
    public static SoundEvent QINGGANG = AllRegs.Sounds.QINGGANG.get();
    public static SoundEvent QINGLONG = AllRegs.Sounds.QINGLONG.get();
    public static SoundEvent TENGJIA1 = AllRegs.Sounds.TENGJIA1.get();
    public static SoundEvent TENGJIA2 = AllRegs.Sounds.TENGJIA2.get();

    public static SoundEvent BINGLIANG = AllRegs.Sounds.BINGLIANG.get();
    public static SoundEvent GUOHE = AllRegs.Sounds.GUOHE.get();
    public static SoundEvent HUOGONG = AllRegs.Sounds.HUOGONG.get();
    public static SoundEvent JIEDAO = AllRegs.Sounds.JIEDAO.get();
    public static SoundEvent JIU = AllRegs.Sounds.JIU.get();
    public static SoundEvent JUEDOU = AllRegs.Sounds.JUEDOU.get();
    public static SoundEvent LEBU = AllRegs.Sounds.LEBU.get();
    public static SoundEvent RECOVER = AllRegs.Sounds.RECOVER.get();
    public static SoundEvent SHAN = AllRegs.Sounds.SHAN.get();
    public static SoundEvent SHUNSHOU = AllRegs.Sounds.SHUNSHOU.get();
    public static SoundEvent TAOYUAN = AllRegs.Sounds.TAOYUAN.get();
    public static SoundEvent TIESUO = AllRegs.Sounds.TIESUO.get();
    public static SoundEvent WANJIAN = AllRegs.Sounds.WANJIAN.get();
    public static SoundEvent WUXIE = AllRegs.Sounds.WUXIE.get();
    public static SoundEvent WUZHONG = AllRegs.Sounds.WUZHONG.get();
    public static SoundEvent NANMAN = AllRegs.Sounds.NANMAN.get();
    public static SoundEvent SHA = AllRegs.Sounds.SHA_FIRE.get();
    public static SoundEvent SHA_FIRE = AllRegs.Sounds.SHA_FIRE.get();
    public static SoundEvent SHA_THUNDER = AllRegs.Sounds.SHA_THUNDER.get();
}
