package com.amotassic.dabaosword.util;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class Sounds {
    public static final DeferredRegister<SoundEvent> SOUNDS = DeferredRegister.create(BuiltInRegistries.SOUND_EVENT, "dabaosword");
    public static final DeferredHolder<SoundEvent, SoundEvent> LET_ME_CC = SOUNDS.register("letmecc", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "letmecc")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LONGDAN1 = SOUNDS.register("longdan1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "longdan1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LONGDAN2 = SOUNDS.register("longdan2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "longdan2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> GONGXIN1 = SOUNDS.register("gongxin1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "gongxin1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> GONGXIN2 = SOUNDS.register("gongxin2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "gongxin2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> ZHIJIAN1 = SOUNDS.register("zhijian1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "zhijian1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> ZHIJIAN2 = SOUNDS.register("zhijian2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "zhijian2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> SHANZHUAN1 = SOUNDS.register("shanzhuan1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "shanzhuan1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> SHANZHUAN2 = SOUNDS.register("shanzhuan2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "shanzhuan2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> RENDE1 = SOUNDS.register("rende1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "rende1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> RENDE2 = SOUNDS.register("rende2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "rende2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> ZHIHENG1 = SOUNDS.register("zhiheng1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "zhiheng1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> ZHIHENG2 = SOUNDS.register("zhiheng2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "zhiheng2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> BUQU1 = SOUNDS.register("buqu1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "buqu1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> BUQU2 = SOUNDS.register("buqu2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "buqu2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> TIEJI1 = SOUNDS.register("tieji1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "tieji1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> TIEJI2 = SOUNDS.register("tieji2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "tieji2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> GANGLIE1 = SOUNDS.register("ganglie1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "ganglie1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> GANGLIE2 = SOUNDS.register("ganglie2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "ganglie2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> FANGZHU1 = SOUNDS.register("fangzhu1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "fangzhu1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> FANGZHU2 = SOUNDS.register("fangzhu2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "fangzhu2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> XINGSHANG1 = SOUNDS.register("xingshang1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "xingshang1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> XINGSHANG2 = SOUNDS.register("xingshang2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "xingshang2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> CHENGLVE1 = SOUNDS.register("chenglve1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "chenglve1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> CHENGLVE2 = SOUNDS.register("chenglve2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "chenglve2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> CUNMU1 = SOUNDS.register("cunmu1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "cunmu1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> CUNMU2 = SOUNDS.register("cunmu2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "cunmu2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> SHICAI1 = SOUNDS.register("shicai1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "shicai1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> SHICAI2 = SOUNDS.register("shicai2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "shicai2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> XUYOU = SOUNDS.register("xuyou", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "xuyou")));
    public static final DeferredHolder<SoundEvent, SoundEvent> DUANLIANG1 = SOUNDS.register("duanliang1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "duanliang1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> DUANLIANG2 = SOUNDS.register("duanliang2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "duanliang2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LUOSHEN1 = SOUNDS.register("luoshen1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "luoshen1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LUOSHEN2 = SOUNDS.register("luoshen2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "luoshen2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> QIXI1 = SOUNDS.register("qixi1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "qixi1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> QIXI2 = SOUNDS.register("qixi2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "qixi2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> QINGGUO1 = SOUNDS.register("qingguo1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "qingguo1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> QINGGUO2 = SOUNDS.register("qingguo2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "qingguo2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LIEGONG1 = SOUNDS.register("liegong1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "liegong1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LIEGONG2 = SOUNDS.register("liegong2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "liegong2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> GONGAO1 = SOUNDS.register("gongao1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "gongao1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> GONGAO2 = SOUNDS.register("gongao2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "gongao2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> WEIZHONG = SOUNDS.register("weizhong", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "weizhong")));
    public static final DeferredHolder<SoundEvent, SoundEvent> BENXI1 = SOUNDS.register("benxi1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "benxi1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> BENXI2 = SOUNDS.register("benxi2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "benxi2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LEIJI1 = SOUNDS.register("leiji1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "leiji1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LEIJI2 = SOUNDS.register("leiji2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "leiji2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> GIFTBOX = SOUNDS.register("giftbox", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "giftbox")));
    public static final DeferredHolder<SoundEvent, SoundEvent> KANPO1 = SOUNDS.register("kanpo1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "kanpo1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> KANPO2 = SOUNDS.register("kanpo2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "kanpo2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> GUOSE1 = SOUNDS.register("guose1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "guose1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> GUOSE2 = SOUNDS.register("guose2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "guose2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LIULI1 = SOUNDS.register("liuli1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "liuli1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LIULI2 = SOUNDS.register("liuli2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "liuli2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> JUEQING1 = SOUNDS.register("jueqing1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "jueqing1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> JUEQING2 = SOUNDS.register("jueqing2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "jueqing2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LUANJI1 = SOUNDS.register("luanji1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "luanji1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LUANJI2 = SOUNDS.register("luanji2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "luanji2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LUANJI3 = SOUNDS.register("luanji3", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "luanji3")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LUANJI4 = SOUNDS.register("luanji4", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "luanji4")));
    public static final DeferredHolder<SoundEvent, SoundEvent> KUROU1 = SOUNDS.register("kurou1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "kurou1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> KUROU2 = SOUNDS.register("kurou2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "kurou2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> JIZHI1 = SOUNDS.register("jizhi1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "jizhi1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> JIZHI2 = SOUNDS.register("jizhi2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "jizhi2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> QICE1 = SOUNDS.register("qice1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "qice1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> QICE2 = SOUNDS.register("qice2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "qice2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LUOYI1 = SOUNDS.register("luoyi1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "luoyi1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LUOYI2 = SOUNDS.register("luoyi2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "luoyi2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> HUOJI1 = SOUNDS.register("huoji1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "huoji1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> HUOJI2 = SOUNDS.register("huoji2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "huoji2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> QUANJI1 = SOUNDS.register("quanji1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "quanji1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> QUANJI2 = SOUNDS.register("quanji2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "quanji2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> ZILI1 = SOUNDS.register("zili1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "zili1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> ZILI2 = SOUNDS.register("zili2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "zili2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> PAIYI1 = SOUNDS.register("paiyi1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "paiyi1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> PAIYI2 = SOUNDS.register("paiyi2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "paiyi2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> PAIYI3 = SOUNDS.register("paiyi3", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "paiyi3")));
    public static final DeferredHolder<SoundEvent, SoundEvent> PAIYI4 = SOUNDS.register("paiyi4", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "paiyi4")));
    public static final DeferredHolder<SoundEvent, SoundEvent> YIJI1 = SOUNDS.register("yiji1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "yiji1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> YIJI2 = SOUNDS.register("yiji2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "yiji2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> TAOLUAN1 = SOUNDS.register("taoluan1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "taoluan1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> TAOLUAN2 = SOUNDS.register("taoluan2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "taoluan2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> POJUN1 = SOUNDS.register("pojun1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "pojun1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> POJUN2 = SOUNDS.register("pojun2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "pojun2")));
    public static final DeferredHolder<SoundEvent, SoundEvent> KUANGGU1 = SOUNDS.register("kuanggu1", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "kuanggu1")));
    public static final DeferredHolder<SoundEvent, SoundEvent> KUANGGU2 = SOUNDS.register("kuanggu2", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "kuanggu2")));


    public static final DeferredHolder<SoundEvent, SoundEvent> BINGLIANG = SOUNDS.register("bingliang", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "bingliang")));
    public static final DeferredHolder<SoundEvent, SoundEvent> GUOHE = SOUNDS.register("guohe", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "guohe")));
    public static final DeferredHolder<SoundEvent, SoundEvent> HUOGONG = SOUNDS.register("huogong", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "huogong")));
    public static final DeferredHolder<SoundEvent, SoundEvent> JIEDAO = SOUNDS.register("jiedao", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "jiedao")));
    public static final DeferredHolder<SoundEvent, SoundEvent> JIU = SOUNDS.register("jiu", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "jiu")));
    public static final DeferredHolder<SoundEvent, SoundEvent> JUEDOU = SOUNDS.register("juedou", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "juedou")));
    public static final DeferredHolder<SoundEvent, SoundEvent> LEBU = SOUNDS.register("lebu", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "lebu")));
    public static final DeferredHolder<SoundEvent, SoundEvent> RECOVER = SOUNDS.register("recover", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "recover")));
    public static final DeferredHolder<SoundEvent, SoundEvent> SHAN = SOUNDS.register("shan", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "shan")));
    public static final DeferredHolder<SoundEvent, SoundEvent> SHUNSHOU = SOUNDS.register("shunshou", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "shunshou")));
    public static final DeferredHolder<SoundEvent, SoundEvent> TAOYUAN = SOUNDS.register("taoyuan", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "taoyuan")));
    public static final DeferredHolder<SoundEvent, SoundEvent> TIESUO = SOUNDS.register("tiesuo", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "tiesuo")));
    public static final DeferredHolder<SoundEvent, SoundEvent> WANJIAN = SOUNDS.register("wanjian", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "wanjian")));
    public static final DeferredHolder<SoundEvent, SoundEvent> WUXIE = SOUNDS.register("wuxie", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "wuxie")));
    public static final DeferredHolder<SoundEvent, SoundEvent> WUZHONG = SOUNDS.register("wuzhong", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "wuzhong")));
    public static final DeferredHolder<SoundEvent, SoundEvent> NANMAN = SOUNDS.register("nanman", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "nanman")));
    public static final DeferredHolder<SoundEvent, SoundEvent> SHA = SOUNDS.register("sha", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "sha")));
    public static final DeferredHolder<SoundEvent, SoundEvent> SHA_FIRE = SOUNDS.register("sha_fire", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "sha_fire")));
    public static final DeferredHolder<SoundEvent, SoundEvent> SHA_THUNDER = SOUNDS.register("sha_thunder", () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath("dabaosword", "sha_thunder")));
}
