package com.amotassic.dabaosword.util;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class Sounds {
    public static final DeferredRegister<SoundEvent> SOUNDS = DeferredRegister.create(BuiltInRegistries.SOUND_EVENT, "dabaosword");
    public static final DeferredHolder<SoundEvent, SoundEvent> LIANYING1 = register("lianying1");
    public static final DeferredHolder<SoundEvent, SoundEvent> LIANYING2 = register("lianying2");
    public static final DeferredHolder<SoundEvent, SoundEvent> XIAOJI1 = register("xiaoji1");
    public static final DeferredHolder<SoundEvent, SoundEvent> XIAOJI2 = register("xiaoji2");
    public static final DeferredHolder<SoundEvent, SoundEvent> LET_ME_CC = register("letmecc");
    public static final DeferredHolder<SoundEvent, SoundEvent> LONGDAN1 = register("longdan1");
    public static final DeferredHolder<SoundEvent, SoundEvent> LONGDAN2 = register("longdan2");
    public static final DeferredHolder<SoundEvent, SoundEvent> GONGXIN1 = register("gongxin1");
    public static final DeferredHolder<SoundEvent, SoundEvent> GONGXIN2 = register("gongxin2");
    public static final DeferredHolder<SoundEvent, SoundEvent> ZHIJIAN1 = register("zhijian1");
    public static final DeferredHolder<SoundEvent, SoundEvent> ZHIJIAN2 = register("zhijian2");
    public static final DeferredHolder<SoundEvent, SoundEvent> SHANZHUAN1 = register("shanzhuan1");
    public static final DeferredHolder<SoundEvent, SoundEvent> SHANZHUAN2 = register("shanzhuan2");
    public static final DeferredHolder<SoundEvent, SoundEvent> RENDE1 = register("rende1");
    public static final DeferredHolder<SoundEvent, SoundEvent> RENDE2 = register("rende2");
    public static final DeferredHolder<SoundEvent, SoundEvent> ZHIHENG1 = register("zhiheng1");
    public static final DeferredHolder<SoundEvent, SoundEvent> ZHIHENG2 = register("zhiheng2");
    public static final DeferredHolder<SoundEvent, SoundEvent> BUQU1 = register("buqu1");
    public static final DeferredHolder<SoundEvent, SoundEvent> BUQU2 = register("buqu2");
    public static final DeferredHolder<SoundEvent, SoundEvent> TIEJI1 = register("tieji1");
    public static final DeferredHolder<SoundEvent, SoundEvent> TIEJI2 = register("tieji2");
    public static final DeferredHolder<SoundEvent, SoundEvent> GANGLIE1 = register("ganglie1");
    public static final DeferredHolder<SoundEvent, SoundEvent> GANGLIE2 = register("ganglie2");
    public static final DeferredHolder<SoundEvent, SoundEvent> FANGZHU1 = register("fangzhu1");
    public static final DeferredHolder<SoundEvent, SoundEvent> FANGZHU2 = register("fangzhu2");
    public static final DeferredHolder<SoundEvent, SoundEvent> XINGSHANG1 = register("xingshang1");
    public static final DeferredHolder<SoundEvent, SoundEvent> XINGSHANG2 = register("xingshang2");
    public static final DeferredHolder<SoundEvent, SoundEvent> CHENGLVE1 = register("chenglve1");
    public static final DeferredHolder<SoundEvent, SoundEvent> CHENGLVE2 = register("chenglve2");
    public static final DeferredHolder<SoundEvent, SoundEvent> CUNMU1 = register("cunmu1");
    public static final DeferredHolder<SoundEvent, SoundEvent> CUNMU2 = register("cunmu2");
    public static final DeferredHolder<SoundEvent, SoundEvent> SHICAI1 = register("shicai1");
    public static final DeferredHolder<SoundEvent, SoundEvent> SHICAI2 = register("shicai2");
    public static final DeferredHolder<SoundEvent, SoundEvent> XUYOU = register("xuyou");
    public static final DeferredHolder<SoundEvent, SoundEvent> DUANLIANG1 = register("duanliang1");
    public static final DeferredHolder<SoundEvent, SoundEvent> DUANLIANG2 = register("duanliang2");
    public static final DeferredHolder<SoundEvent, SoundEvent> LUOSHEN1 = register("luoshen1");
    public static final DeferredHolder<SoundEvent, SoundEvent> LUOSHEN2 = register("luoshen2");
    public static final DeferredHolder<SoundEvent, SoundEvent> QIXI1 = register("qixi1");
    public static final DeferredHolder<SoundEvent, SoundEvent> QIXI2 = register("qixi2");
    public static final DeferredHolder<SoundEvent, SoundEvent> QINGGUO1 = register("qingguo1");
    public static final DeferredHolder<SoundEvent, SoundEvent> QINGGUO2 = register("qingguo2");
    public static final DeferredHolder<SoundEvent, SoundEvent> LIEGONG1 = register("liegong1");
    public static final DeferredHolder<SoundEvent, SoundEvent> LIEGONG2 = register("liegong2");
    public static final DeferredHolder<SoundEvent, SoundEvent> GONGAO1 = register("gongao1");
    public static final DeferredHolder<SoundEvent, SoundEvent> GONGAO2 = register("gongao2");
    public static final DeferredHolder<SoundEvent, SoundEvent> WEIZHONG = register("weizhong");
    public static final DeferredHolder<SoundEvent, SoundEvent> BENXI1 = register("benxi1");
    public static final DeferredHolder<SoundEvent, SoundEvent> BENXI2 = register("benxi2");
    public static final DeferredHolder<SoundEvent, SoundEvent> LEIJI1 = register("leiji1");
    public static final DeferredHolder<SoundEvent, SoundEvent> LEIJI2 = register("leiji2");
    public static final DeferredHolder<SoundEvent, SoundEvent> GIFTBOX = register("giftbox");
    public static final DeferredHolder<SoundEvent, SoundEvent> KANPO1 = register("kanpo1");
    public static final DeferredHolder<SoundEvent, SoundEvent> KANPO2 = register("kanpo2");
    public static final DeferredHolder<SoundEvent, SoundEvent> GUOSE1 = register("guose1");
    public static final DeferredHolder<SoundEvent, SoundEvent> GUOSE2 = register("guose2");
    public static final DeferredHolder<SoundEvent, SoundEvent> LIULI1 = register("liuli1");
    public static final DeferredHolder<SoundEvent, SoundEvent> LIULI2 = register("liuli2");
    public static final DeferredHolder<SoundEvent, SoundEvent> JUEQING1 = register("jueqing1");
    public static final DeferredHolder<SoundEvent, SoundEvent> JUEQING2 = register("jueqing2");
    public static final DeferredHolder<SoundEvent, SoundEvent> LUANJI1 = register("luanji1");
    public static final DeferredHolder<SoundEvent, SoundEvent> LUANJI2 = register("luanji2");
    public static final DeferredHolder<SoundEvent, SoundEvent> LUANJI3 = register("luanji3");
    public static final DeferredHolder<SoundEvent, SoundEvent> LUANJI4 = register("luanji4");
    public static final DeferredHolder<SoundEvent, SoundEvent> KUROU1 = register("kurou1");
    public static final DeferredHolder<SoundEvent, SoundEvent> KUROU2 = register("kurou2");
    public static final DeferredHolder<SoundEvent, SoundEvent> JIZHI1 = register("jizhi1");
    public static final DeferredHolder<SoundEvent, SoundEvent> JIZHI2 = register("jizhi2");
    public static final DeferredHolder<SoundEvent, SoundEvent> QICE1 = register("qice1");
    public static final DeferredHolder<SoundEvent, SoundEvent> QICE2 = register("qice2");
    public static final DeferredHolder<SoundEvent, SoundEvent> LUOYI1 = register("luoyi1");
    public static final DeferredHolder<SoundEvent, SoundEvent> LUOYI2 = register("luoyi2");
    public static final DeferredHolder<SoundEvent, SoundEvent> HUOJI1 = register("huoji1");
    public static final DeferredHolder<SoundEvent, SoundEvent> HUOJI2 = register("huoji2");
    public static final DeferredHolder<SoundEvent, SoundEvent> QUANJI1 = register("quanji1");
    public static final DeferredHolder<SoundEvent, SoundEvent> QUANJI2 = register("quanji2");
    public static final DeferredHolder<SoundEvent, SoundEvent> ZILI1 = register("zili1");
    public static final DeferredHolder<SoundEvent, SoundEvent> ZILI2 = register("zili2");
    public static final DeferredHolder<SoundEvent, SoundEvent> PAIYI1 = register("paiyi1");
    public static final DeferredHolder<SoundEvent, SoundEvent> PAIYI2 = register("paiyi2");
    public static final DeferredHolder<SoundEvent, SoundEvent> PAIYI3 = register("paiyi3");
    public static final DeferredHolder<SoundEvent, SoundEvent> PAIYI4 = register("paiyi4");
    public static final DeferredHolder<SoundEvent, SoundEvent> YIJI1 = register("yiji1");
    public static final DeferredHolder<SoundEvent, SoundEvent> YIJI2 = register("yiji2");
    public static final DeferredHolder<SoundEvent, SoundEvent> TAOLUAN1 = register("taoluan1");
    public static final DeferredHolder<SoundEvent, SoundEvent> TAOLUAN2 = register("taoluan2");
    public static final DeferredHolder<SoundEvent, SoundEvent> POJUN1 = register("pojun1");
    public static final DeferredHolder<SoundEvent, SoundEvent> POJUN2 = register("pojun2");
    public static final DeferredHolder<SoundEvent, SoundEvent> KUANGGU1 = register("kuanggu1");
    public static final DeferredHolder<SoundEvent, SoundEvent> KUANGGU2 = register("kuanggu2");

    public static final DeferredHolder<SoundEvent, SoundEvent> BINGLIANG = register("bingliang");
    public static final DeferredHolder<SoundEvent, SoundEvent> GUOHE = register("guohe");
    public static final DeferredHolder<SoundEvent, SoundEvent> HUOGONG = register("huogong");
    public static final DeferredHolder<SoundEvent, SoundEvent> JIEDAO = register("jiedao");
    public static final DeferredHolder<SoundEvent, SoundEvent> JIU = register("jiu");
    public static final DeferredHolder<SoundEvent, SoundEvent> JUEDOU = register("juedou");
    public static final DeferredHolder<SoundEvent, SoundEvent> LEBU = register("lebu");
    public static final DeferredHolder<SoundEvent, SoundEvent> RECOVER = register("recover");
    public static final DeferredHolder<SoundEvent, SoundEvent> SHAN = register("shan");
    public static final DeferredHolder<SoundEvent, SoundEvent> SHUNSHOU = register("shunshou");
    public static final DeferredHolder<SoundEvent, SoundEvent> TAOYUAN = register("taoyuan");
    public static final DeferredHolder<SoundEvent, SoundEvent> TIESUO = register("tiesuo");
    public static final DeferredHolder<SoundEvent, SoundEvent> WANJIAN = register("wanjian");
    public static final DeferredHolder<SoundEvent, SoundEvent> WUXIE = register("wuxie");
    public static final DeferredHolder<SoundEvent, SoundEvent> WUZHONG = register("wuzhong");
    public static final DeferredHolder<SoundEvent, SoundEvent> NANMAN = register("nanman");
    public static final DeferredHolder<SoundEvent, SoundEvent> SHA = register("sha");
    public static final DeferredHolder<SoundEvent, SoundEvent> SHA_FIRE = register("sha_fire");
    public static final DeferredHolder<SoundEvent, SoundEvent> SHA_THUNDER = register("sha_thunder");

    public static DeferredHolder<SoundEvent, SoundEvent> register(String name){
        ResourceLocation location = ResourceLocation.fromNamespaceAndPath("dabaosword", name);
        return SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(location));
    }
}
